### ISSUE TITLE
usage clarifications for causal-cmd (

### ISSUE THREAD

**Issue by espinoj** [bd2kccd/causal-cmd#22]
When I run the causal cmd without any arguments, I don't see all of the usage details. Is it possible to change he default usage code to indicate that "--algorithm xxx" should be specified for usage details on algorithm xxx?

Also remove old json output feature.  Keep the new one.

**Comment by kvb2univpitt** [comment]
For the first issue, I don't see what the problem is.  I do see usage detail when running causal-cmd without any argument.  See below.  Can you please clarify?
`java -jar causal-cmd-0.2.0.jar`
```
usage: java -jar causal-cmd-0.2.0.jar --algorithm <arg> | --simulate-data <arg>  [--version]
    --algorithm <arg>       FGESc, FGESd, FGESm-cg, GFCIc, GFCId, GFCIm-cg
    --simulate-data <arg>   sem-rand-fwd, bayes-net-rand-fwd, lee-hastie
    --version               Show software version.
Additional parameters are available when using --algorithm <arg> or --simulate-data <arg>.
 ```
For the second issue, yes.  We can remove any unused switch.  Will work on this.

**Comment by espinoj** [comment]
@kvb2univpitt  Decision is to hide --json

**Comment by kvb2univpitt** [comment]
To keep the code clean, can we just completely remove it?  We can always put it back if we ever need it, since we tagged previous versions of it.

**Comment by espinoj** [comment]
harry still needs it but for general users it is confusing

**Comment by kvb2univpitt** [comment]
We are using the Apache CLI library to parse the command line inputs.  If we remove the json option to hide it from the user, the Apache CLI will scream "Unrecognized option" if Harry tries to pass it in.

**Comment by kvb2univpitt** [comment]
@espinoj @harryhoch Ok.  I created a method to work around that.  --json switch is now hidden from the user but still available.

**Comment by espinoj** [comment]
@kvb2univpitt  Creativity!!!
