### ISSUE TITLE
Changing Parameter Values failing in causal-cmd

### ISSUE THREAD

**Issue by kshajih1** [bd2kccd/causal-cmd#27]
After reading the CCD Usage Guide, I have attempted to adjust parameters on the FGESd algorithm with the following line:

java -jar causalcmd6.1.jar --algorithm FGESd -f /path/to/file [--sample-prior 2.0] [--structure-prior 1.0]

On my output in terminal, however, I get the output shown in the screenshot attached. Am I not adjusting the parameters correctly? This seems like a fairly obvious issue, but I can't seem to get this worked out.

Thank you.

<img width="398" alt="screen shot 2017-06-30 at 6 52 59 pm" src="https://user-images.githubusercontent.com/29383575/27756443-661ffc26-5dc5-11e7-9db9-98de52e0d3f1.png">

**Comment by kvb2univpitt** [comment]
Sorry for the late response.  Did you ever get it working?
