### ISSUE TITLE
fges penalty discount not working

### ISSUE THREAD

**Issue by rubenSaro** [bd2kccd/causal-cmd#48]
@kvb2univpitt Hi,

I checked the new release (1.1.2) and you do not get the error regarding the penaltyDiscount, but the algorithm seems to be not using that info., and probably running at its default value. 

I tried different penaltyDiscount values, and always got the same graph. 

Also, in the txt output you cannot see which value of penaltyDiscount you entered, it is not listed in the parameters list.

Ruben

**Comment by kvb2univpitt** [comment]
@rubenSaro Thanks. I'll take a look at it and get back to you.

**Comment by kvb2univpitt** [comment]
@rubenSaro OK.  It's now fixed.  I tested it.  The penaltyDiscount parameter now work.  Thanks.

**Comment by jdramsey** [comment]
Yayyyyyy! -Joe

**Comment by rubenSaro** [comment]
Thanks a lot Kevin !!!
