### ISSUE TITLE
IMaGES not using the penalty parameter

### ISSUE THREAD

**Issue by rubenSaro** [bd2kccd/causal-cmd#51]
@kvb2univpitt in the 1.1.3 release, the fGES algorithm now works ok, but the IMaGES algorithm still output an error when input the penaltyDiscount parameter

**Comment by kvb2univpitt** [comment]
@rubenSaro That's strange.  I'll take a look at it today.  Thanks.

**Comment by kvb2univpitt** [comment]
@rubenSaro Both IMaGES Discrete and IMaGES Continuous don't take either test or score.  Therefore, there's no penaltyDiscount parameter for it.  See screenshots of tetrad-gui below:
![img_cont](https://user-images.githubusercontent.com/10729309/68223260-77c65f80-ffba-11e9-89f9-aa679103cabd.png)

![img_disc](https://user-images.githubusercontent.com/10729309/68223272-7ac15000-ffba-11e9-8d53-653a48b6f1f0.png)

**Comment by rubenSaro** [comment]
@kvb2univpitt @espinoj  That is weird. Those algorithms are based on fGES so they should take as a parameter the penalty discount. My take then is that the GUI also have a bug.

**Comment by kvb2univpitt** [comment]
@rubenSaro @espinoj @jdramsey  IMaGES Discrete uses ImagesBDeu which is using BDeu score.  However,  parameters for sample prior and structure prior are not exposed as it should be.  You're right.  There's a bug and I know exactly why.  The method getParameters() of the algorithms are using the old way of getting parameters.  Thus, it's only getting the parameters for the algorithm and not the score, as shown below:
```List<String> parameters = new Fges(new BdeuScore(), false).getParameters();```

The correct way would be this:
```java
List<String> parameters = new LinkedList<>();
parameters.addAll((new Fges()).getParameters());
parameters.addAll((new BdeuScore()).getParameters());
```
We need to fix this for all algorithms.

**Comment by jdramsey** [comment]
I think the issue here is that those parameters need to be given explicitly for those algorithms; there was an issue with allowing those algorithms to take an arbitrary score, so the score parameters had to be given as algorithm parameters. I think if you just add those parameters to the algorithms they should be extraordinarily happy.

**Comment by kvb2univpitt** [comment]
@rubenSaro This is now fixed in tetrad 6.8.0-SNAPSHOT.  The causal-cmd in the development branch uses tetrad 6.8.0-SNAPSHOT.  You can compile causal-cmd from the development branch and use it.  You should penaltyDiscount parameter for IMaGES.

**Comment by rubenSaro** [comment]
thanks Kevin, I will check it out.

ruben

**Comment by espinoj** [comment]
@rubenSaro we also have latest downloadable compiled versions at https://cloud.ccd.pitt.edu/latest-dev-tetrad.html

**Comment by espinoj** [comment]
@rubenSaro 
for causal cmd too!
https://cloud.ccd.pitt.edu/latest-dev-causalcmd.html

**Comment by kvb2univpitt** [comment]
@espinoj  The link above for causal-cmd does not have the latest changes.  It's using tetrad 6.7.0, which doesn't have the changes I made today.

**Comment by espinoj** [comment]
@kvb2univpitt Ok.  I see.  We must have changed something since the auto snapshots on our maven repo don't seem to be up to date.  I'll fix.
