### ISSUE TITLE
Warning in compilation

### ISSUE THREAD

**Issue by imichalop** [bd2kccd/causal-cmd#52]
Hi there!

I tried:

mvn package

using java version "14.0.1" and openjdk version "11.0.7" and I get the following warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

When I downgraded to java version "1.8.0_251", I got no warnings. Any idea?

Best Regards,

Ioannis

**Comment by kvb2univpitt** [comment]
Hello.  Causal-cmd was built and tested on JDK8.  Therefore, only Java 8 is supported.  We are planning on moving forward with the new version of OpenJDK in the future.  Please use Java 8 for now.  Thanks.

**Comment by imichalop** [comment]
Dear Kevin,
Thank you for your prompt answer! I use Java 8 for now, as you suggested...
Best Regards,
Ioannis

**Comment by kvb2univpitt** [comment]
I am glad it's working for you.
