### ISSUE TITLE
Warning in running

### ISSUE THREAD

**Issue by imichalop** [bd2kccd/causal-cmd#53]
Hi again,
I compiled and I ran causal-cmd in Java 8. When I run it, I get the following warning message:

WARNING: Prefs file removed in background /home/user/.java/.userPrefs/prefs.xml

The output I get is the same with that of GUI Tetrad. Should I worry?

Best Regards,

Ioannis

**Comment by kvb2univpitt** [comment]
Hello.
Please ignore the message;it's harmless.  The message came from one of the libraries that we used.  I doesn't affect the functionalities of the program.

**Comment by imichalop** [comment]
Dear Kevin,
Thank you for your prompt answer!
Best Regards,
Ioannis

**Comment by kvb2univpitt** [comment]
You are welcome.
