### ISSUE TITLE
resampling not working

### ISSUE THREAD

**Issue by dmalinsk** [bd2kccd/causal-cmd#61]
Using causal-cmd version 1.2.1

trying to execute:
> java -jar causal-cmd-1.2.1-jar-with-dependencies.jar --algorithm pc-all --data-type continuous --dataset Retention.txt --delimiter tab --test fisher-z-test --addOriginalDataset Yes --numberResampling 100 --percentResamepleSize 100 --resamplingEnsemble 2 --resamplingWithReplacement Yes

(this is just using the Retention.txt data set packed with causal-cmd for reproducibility)

and it isn't recognizing the resampling commands.

I saw that someone raised this issue for FGES a while ago, but doesn't seem to work with PC either. Any help would be appreciated, thanks!

**Comment by dmalinsk** [comment]
@kvb2univpitt or anyone else -- just checking if this issue is known or addressable?

**Comment by jdramsey** [comment]
@dmalinsk Sorry, Dan, I don't know how to address this.

**Comment by kvb2univpitt** [comment]
@dmalinsk Sorry for the late reply.  I have been extremely busy with other projects.  I can take a look at it this weekend.

**Comment by kvb2univpitt** [comment]
@dmalinsk @jdramsey I finally got the time to work on this issue.  Sorry for the delay.  I fixed the missing bootstrap parameters.  Everything is working now.  However, I am holding off on making an official release containing this fix until I make an official release of Tetrad 6.8.1 that contains Joe's bug fix of the knowledge file.  I will let you know when that's done.  I will be either tomorrow or Monday.  Again, sorry for the delay.

**Comment by kvb2univpitt** [comment]
@dmalinsk @jdramsey  I've made an official release of 1.2.2 that fixes this issue.  Please checkout the latest release.  Also, I've also update tetrad-lib dependency to version 6.8.1.  Some of the parameter names has changed.  For an example, "structurePrior" is now "semBicStructurePrior."
