### ISSUE TITLE
Format of —exclude file

### ISSUE THREAD

**Issue by numair1** [bd2kccd/causal-cmd#65]
In the flags I noticed an option to exclude vars, and the description says to include a file of variables to exclude. What should be the format of this file as I couldn’t find it in any of the documentation.

**Comment by kvb2univpitt** [comment]
@numair1 Unfortunately, our documentation is not up-to-date as I would like it to be.  The format of the file containing variables to be excluded is just the name of the variable on each row.  For an example, let say you want to exclude variables "apple", "orange", and "banana."  The file would look like this:

```
apple
orange
banana
```

The order does not matter.  Here's an example of a variable file [exclude_vars.txt](https://github.com/bd2kccd/causal-cmd/blob/development/src/test/resources/data/exclude_vars.txt).

Hope that helps.

**Comment by jdramsey** [comment]
Asked and answered, closing.
