### ISSUE TITLE
https certificate expired for https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/pitt/dbmi/causal-cmd/ 

### ISSUE THREAD

**Issue by MikeKonrad** [bd2kccd/causal-cmd#66]
A coworker is interested in running causal-cmd and so I revisited the installation and documentation sites to give him the links/URLs he needs. The documentation site comes up fine, but the installation site:
https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/pitt/dbmi/causal-cmd/
Comes up as "Not secure" and we have to be persistent to finally get to the site.

Will HTTPS certificate renewal happen soon?

**Comment by kvb2univpitt** [comment]
@espinoj Any update on the certificate?

**Comment by jmaasch** [comment]
I am still encountering this problem when trying to access the jar file.

**Comment by kvb2univpitt** [comment]
@jmaasch Please download the latest release causal-cmd-1.4.1.  This problem is fixed in this release.

**Comment by jdramsey** [comment]
All downloads have been moved to Maven Central, here:

https://s01.oss.sonatype.org/content/repositories/releases/io/github/cmu-phil/causal-cmd/

There should be no such security issues there. Closing the issue.
