### ISSUE TITLE
Error when using pc algorithm

### ISSUE THREAD

**Issue by Zarmas** [bd2kccd/causal-cmd#75]
Hello,

I am trying to make a causal inference study, on a 14 thread and 128gb RAM system. The full dataset I enter consists of approximately 20000 continuous variables and 3500 samples.

There seems to be a problem when using some pc-related algorithms (ie pc, cpc, pcmax). The type of the error is "java.lang.IllegalArgumentException: Cannot format given Object as a Number", and I have attached the full error message. I got this error message when I tried using all mentioned algorithms and in any variable/sample size.

Thank you in advance,
George

[IllegalArgumentException.txt](https://github.com/bd2kccd/causal-cmd/files/9423485/IllegalArgumentException.txt)

**Comment by jdramsey** [comment]
@Zarmas Sorry I haven't been looking at issues in this project. It seems you are trying to use maybe the SEM BIC test? Could you try another like Fisher Z?

Also could you give me the full causal-cmd string you're using? I've recently become more familiar with this and maybe could help. (I usually work on the Tetrad side, so if it's an issue in Tetrad I should be able to fix it.)

**Comment by jdramsey** [comment]
@Zarmas I take if you're no longer working on this. I'll close it, but if you are still interested in it let us know.
