### ISSUE TITLE
expect a python version

### ISSUE THREAD

**Issue by chxliou** [bd2kccd/causal-cmd#77]
I don't know whether this project is still under maintenance...

**Comment by kvb2univpitt** [comment]
@chxliou The Java version, which is this repository, is still under maintenance.

**Comment by jdramsey** [comment]
@chxliou Are you still trying to run causal-cmd in Python? I can tell you how to do it if you're still interested; it's not hard. (Sorry, I'm just now going through these causal-cmd issues, seeing what I can add.) Last summer we'd some work in this direction; here's a script for that time, though it needs to be updated in obvious ways (i.e., to use more recent releases of causal-cmd):

https://github.com/cmu-phil/algocompy/blob/main/causalcmd/tetrad_cmd_algs.py

Also, if you're interested in Python-specific code for _some_ of the Tetrad algorithms, you can look at the causal-learn package (google it). It's now part of py-why and is actively maintained by people who will respond to your issue requests.

The old pycausal is no longer maintained, as there were some issues with the java-bridge API it was using. I may at some point try to update that, but last we tried it was buggy.

**Comment by jdramsey** [comment]
Oh, also, causal-learn has recently been moved into the py-why space, so you should look for it there. But if you do a google search the references should be up-to-date.

**Comment by jdramsey** [comment]
I will undertake sometime in the next few days to update the scripts I linked to so it's easier to use. I'll let you know. How about this: We're planning to do a new release of both Tetrad and causal-cmd soon,

https://github.com/cmu-phil/tetrad/wiki/Forthcoming-fixes-for-7.1.3_2

Once that is released, I'll go back to the algcompy project and update those scripts and let you know.

To be completely fair, I'm not against updating pycausal using the java bridge and updating the version of causal-cmd it uses; I just need to see if there's a new version of the java bridge that's less buggy before committing any real effort to it.

**Comment by jdramsey** [comment]
@chxliou I don't know if you've been watching; we added a new package to show how to incorporate Tetrad into Python using JPype. It works well. The project is not finished yet, but JPype works like a charm.

See the Python Integration pointers at https://github.com/cmu-phil/tetrad.

**Comment by jdramsey** [comment]
I looks like this is a stale issue, closing.
