### ISSUE TITLE
unresolvable dependency

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/causal-cmd#8]
[install_log.txt](https://github.com/bd2kccd/causal-cmd/files/917756/install_log.txt)

**Comment by kingfish777** [comment]
... ditto with jdk1.8u31

**Comment by espinoj** [comment]
Please do a repull of the branch (master or development) and rebuild.  We have moved the dependency server to another machine due to SSL certificate problems at PSC.

**Comment by kingfish777** [comment]
We are experiencing issues with javax.xml.parsers.FactoryConfiguration / tetradLogger with r-causal as well. Seems to have something to do with the data reader.

Where can I find that?


Was trying to hit PSC, but yes experiencing ssl problems.

 -S

________________________________

**Comment by kingfish777** [comment]
From current causal-cmd-development.zip: 
[mvn-install.txt](https://github.com/bd2kccd/causal-cmd/files/917833/mvn-install.txt)

**Comment by espinoj** [comment]
@kingfish777 
seeing the same test failures -- only on ubuntu, passes on mac and redhat/centos.
