### ISSUE TITLE
How to specify initial graph for an algorithm in causal-cmd

### ISSUE THREAD

**Issue by jdramsey** [bd2kccd/causal-cmd#85]
The question is simply how to get FASK, e.g., to recognize an "external graph" in causal-cmd... this is just a matter of specifying the initial graph (for any search that takes one)...

This is independent of the question of getting FGES to be followed by a non-Gaussian orientation, sorry.

Several algorithms can take initial graphs; this would be a general feature, maybe --initialGraph graph.txt or some such.

**Comment by kvb2univpitt** [comment]
I can add that feature in causal-cmd by creating a parameter **_--initial-graph_** to specify the initial graph. We do need another annotation in Tetrad to indicate that an algorithm can take an initial graph.

**Comment by jdramsey** [comment]
This was done--see the tetrad issue mentioned above.
