### ISSUE TITLE
Maven's test process does not work on windows

### ISSUE THREAD

**Issue by yasu-sh** [bd2kccd/causal-cmd#93]
@kvb2univpitt 
This is the console messages on windows when I test at IntelliJ IDEA CE.
Already known workaround: disable test at Maven on Windows.
I will make pull requests later. If developes like to do this and make double-checking on Mac or Unix.

It would be better for windows users. If you should not like to manuplate the code, let me know and I won't do like this.

```
[ERROR] Tests run: 12, Failures: 0, Errors: 5, Skipped: 1, Time elapsed: 0.747 s <<< FAILURE! - in edu.pitt.dbmi.causal.cmd.CausalCmdApplicationTest
[ERROR] testGFCIWithContinuousDataAndVariablesToExclude  Time elapsed: 0.004 s  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /E:/GitLab/causal-cmd/target/test-classes/data/sim_data_continuous_20var_100case.txt
	at edu.pitt.dbmi.causal.cmd.CausalCmdApplicationTest.testGFCIWithContinuousDataAndVariablesToExclude(CausalCmdApplicationTest.java:125)
```

I think this issue has also the same root-cause.
https://github.com/cmu-phil/tetrad/issues/1330#issue-926190136

**Comment by kvb2univpitt** [comment]
@yasu-sh I'll setup a Windows test machine to test and fix this.  Thanks for pointing this out.  I mainly work on Linux.

**Comment by yasu-sh** [comment]
@kvb2univpitt Thanks for your trial. In case I notice similiar issues, I'll open them on github and you can check them once.

**Comment by kvb2univpitt** [comment]
@yasu-sh I see that you made a pull request (https://github.com/bd2kccd/causal-cmd/pull/95).  Is that for fixing this issue?

**Comment by yasu-sh** [comment]
Closing. #95 is merged. @kvb2univpitt Thanks for your checking.
