### ISSUE TITLE
jar-filename is not copied from the argument to usage verbose

### ISSUE THREAD

**Issue by yasu-sh** [bd2kccd/causal-cmd#96]
Thanks for many updates recently.

In previous releases `causal-cmd-1.8.0-jar-with-dependencies.jar` verbose was the same as used in command-line.
Now displayed the different. `Causal-cmd Project-1.8.0.jar` 
I wondered if there were any reasons to use 'Project' keyword.

If there are any good reasons, just close this issue.

PS >  java '-Duser.language=en' -jar `causal-cmd-1.8.0-jar-with-dependencies.jar`   

Missing required options: algorithm, data-type, dataset, delimiter
usage: java -jar `Causal-cmd Project-1.8.0.jar`  --algorithm <string> [--comment-marker <string>] --data-type <string> --dataset <files> [--default] --delimiter <string>    (omit)

**Comment by jdramsey** [comment]
@yasu-sh We need to update our documentation. It's pretty old at this point. Unfortunately, none of us working on the code has access to it currently, so there's some work to be done there.

**Comment by yasu-sh** [comment]
@jdramsey Thanks for your responding. I guess the added code of <name> tag reflects the result. I confirmed when building by myself. 

Regarding the documentation, let's talk on the other issue I already made.

![image](https://user-images.githubusercontent.com/89838961/236766937-7a274b7d-210d-44a0-aea4-2d33b978c763.png)

https://github.com/bd2kccd/causal-cmd/commit/2497dcbbee85890466f4c3da2e8f96dbc76ece3d

https://stackoverflow.com/questions/68321439/how-to-log-the-pom-artifact-and-version

**Comment by yasu-sh** [comment]
I confirmed this issue fixed at ver. 1.10. Even this description does not copy used jar, but the effect is small and we can guess the current jar filename.

> PS >  java '-Duser.language=en' -jar causal-cmd-1.10.0-jar-with-dependencies.jar
> Missing required options: algorithm, data-type, dataset, delimiter
> usage: java -jar causal-cmd-1.10.0.jar  --algorithm <string>
